### ISSUE TITLE
Docs misleading in regards to Paragraph + Inline Toolbar + Plugins

### ISSUE THREAD

**Issue by i8ramin** [Jungwoo-An/react-editor-js#100]
### Environment

- @editorjs/editorjs version: 2.19.1
- react-editor-js version: 1.9.0

### Describe

The current README/Docs mention how to add more tools/plugins by defining a `tools.js` file and adding them all there. However, if one were to blindly copy the sample code given in the README, the [default `inlineToolbar` functionality of `Paragraph`](https://github.com/Jungwoo-An/react-editor-js/blob/1216dce26b260c57e39bf9d311839d15f638faba/lib/EditorJs.tsx#L90) is disabled. I think it is worth mentioning this in the README in/around the ["How can I install plugins"](https://github.com/Jungwoo-An/react-editor-js#how-can-i-install-plugins) section. My workaround is simply not include `Paragraph` as one of the included tools (since it is already included by default).

```js
export const EDITOR_JS_TOOLS = {
  checklist: CheckList,
  code: Code,
  delimiter: Delimiter,
  embed: Embed,
  header: Header,
  image: Image,
  inlineCode: InlineCode,
  linkTool: LinkTool,
  list: List,
  marker: Marker,
  // paragraph: Paragraph,
  quote: Quote,
  raw: Raw,
  simpleImage: SimpleImage,
  table: Table,
  warning: Warning,
}

```

**Comment by Jungwoo-An** [comment]
@i8ramin Hi! First of all, thanks for your interest! 👋 

Wow! This suggestion is really cool. I'll update README.

Thanks!

**Comment by monting** [comment]
Interesting. When I remove `paragraph` from the tools object, I still don't get the inline toolbar, and get this error in the console:

`Saving failed due to the Error TypeError: Cannot read property 'sanitizeConfig' of undefined`


I also get this error when selecting text in the editor. Seems like this is an error rendering the toolbar, because it doesn't render.

`Uncaught TypeError: Cannot read property 'create' of undefined`

**Comment by Jungwoo-An** [comment]
#166
