### ISSUE TITLE
instanceRef.current is undefined

### ISSUE THREAD

**Issue by codigoisaac** [Jungwoo-An/react-editor-js#191]
### Environment

- @editorjs/editorjs version: ^2.23.2
- react-editor-js version: ^2.0.6

### Describe

I'm trying to get the data when hitting save. But I get this error: 
**Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'save')**

I followed [this example](https://codesandbox.io/s/react-editor-js-o2n3b?file=/index.js) and [this other one](https://codesandbox.io/s/react-editor-js-v2-34bfl) (both I found in other issues), but nothing seems to work.

My code: 

```
import { createReactEditorJS } from 'react-editor-js'
import Image from '@editorjs/image'
```
```
const Editor = createReactEditorJS()

const instanceRef = useRef(null);
```
```
async function handleSave() {
  const savedData = await instanceRef.current.save();
  console.log("savedData", savedData);
}
```
```
<Button color='primary' className='text-nowrap px-1 btn-sm' onClick={handleSave} outline>

<Editor
  placeholder="Enunciado da alternativa"
  tools={{ image: Image }}
  instanceRef={instance => (instanceRef.current = instance)}
/>
```

When I press the button:

![ex](https://user-images.githubusercontent.com/37576563/162817018-5d13cd56-cb95-43a0-95e1-87601d4728a6.png)

**Comment by quatre29** [comment]
I get the same issue, any idea how to fix it?

**Comment by AlbinoGeek** [comment]
Try: https://github.com/Jungwoo-An/react-editor-js/issues/190#issuecomment-1105459267

@codigoisaac @quatre29 It works for me in NextJS after doing this.

**Comment by codigoisaac** [comment]
@quatre29 @AlbinoGeek I just switched to TinyMCE (best decision ever). Thanks, guys.

**Comment by AlbinoGeek** [comment]
> @quatre29 @AlbinoGeek I just switched to TinyMCE (best decision ever). Thanks, guys.

Huge mistake, but you do you. EditorJS generates structured JSON describing blocks, TinyMCE generates HTML soup the likes of which we haven't seen since Adobe DreamWeaver, and/or copy-pasting Rich Text from Microsoft Word into a website... the output is completely different, and much worse.

However, I'll admit, TinyMCE lets you do more, because it's plain HTML.

Consider a Google around `The problem with WYSIWYG`. I don't enjoy 100kb if nested `<font>` or `<span>` tags with various once-applied styles, and your browser doesn't either. Perhaps my favourite message on the spaghetti that WYSIWYG editors output is as follows:

```
    * Egg and bacon
    * Egg, sausage and bacon
    * Egg and <span>
    * Egg, bacon and <span>
    * Egg, bacon, sausage and <span>
    * <span>, bacon, sausage and <span>
    * <span>, egg, <span>, <span>, bacon and <span>
    * <span>, <span>, <span>, egg, and <span>
    * <span>, <span>, <span>, <span>, <span>, <span>, baked beans, <span>, <span>, <span> and <span>
    * Lobster thermidor aux crevettes with a Mornay sauce garnished with truffle paté, brandy and with a fried egg on top and <span>
    * <span>, sausage, <span>, <span>, <span>, bacon, <span>, tomato and <span>
```
> https://what.thedailywtf.com/topic/3275/why-wysiwyg-html-editors-should-not-exist/10

---

## Ultimately, if it's no longer your problem, consider closing the issue.

**Comment by quatre29** [comment]
> > @quatre29 @AlbinoGeek I just switched to TinyMCE (best decision ever). Thanks, guys.
> 
> Huge mistake, but you do you. EditorJS generates structured JSON describing blocks, TinyMCE generates HTML soup the likes of which we haven't seen since Adobe DreamWeaver, and/or copy-pasting Rich Text from Microsoft Word into a website... the output is completely different, and much worse.
> 
> However, I'll admit, TinyMCE lets you do more, because it's plain HTML.
> 
> Consider a Google around `The problem with WYSIWYG`. I don't enjoy 100kb if nested `<font>` or `<span>` tags with various once-applied styles, and your browser doesn't either. Perhaps my favourite message on the spaghetti that WYSIWYG editors output is as follows:
> 
> ```
>     * Egg and bacon
>     * Egg, sausage and bacon
>     * Egg and <span>
>     * Egg, bacon and <span>
>     * Egg, bacon, sausage and <span>
>     * <span>, bacon, sausage and <span>
>     * <span>, egg, <span>, <span>, bacon and <span>
>     * <span>, <span>, <span>, egg, and <span>
>     * <span>, <span>, <span>, <span>, <span>, <span>, baked beans, <span>, <span>, <span> and <span>
>     * Lobster thermidor aux crevettes with a Mornay sauce garnished with truffle paté, brandy and with a fried egg on top and <span>
>     * <span>, sausage, <span>, <span>, <span>, bacon, <span>, tomato and <span>
> ```
> 
> > https://what.thedailywtf.com/topic/3275/why-wysiwyg-html-editors-should-not-exist/10
> 
> ## Ultimately, if it's no longer your problem, consider closing the issue.

I'm a beginner and to be honest, I have a hard time implementing a rich text editor that works with embedded videos, uploading images etc. EditorJS is awesome but has a lot of bugs. Do you think WYSIWYG editors would make the application slower?

Also do you experience flickering screen page with react-editor-js?

**Comment by AlbinoGeek** [comment]
> @quatre29
> I'm a beginner and to be honest, I have a hard time implementing a rich text editor that works with embedded videos, uploading images etc. EditorJS is awesome but has a lot of bugs. Do you think WYSIWYG editors would make the application slower?

## **[TLDR, my editor is open source, you could just use that.](https://github.com/Rethunk-Tech/nextjs-boilerplate)**

### Regarding "Bugs"

Honestly, if you follow the two step instructions in [my workaround here](https://github.com/Jungwoo-An/react-editor-js/issues/190#issuecomment-1105459267), there are very few bugs remaining. EditorJS is actively maintained, and the only bugs I've run into so far are relatively minor (like scrolling suppressed when `autofocus={true}`, which was easy to document around.)

![image](https://user-images.githubusercontent.com/1910461/166142741-631f07bd-2fdf-42c3-8752-2a0c1ab3c312.png)

### Regarding "Uploading images"

I've not implemented uploading images yet (that image is by URL), although `@editorjs/image` supports this out of the box if you're okay with using things "as is" (I'm not one of those people, so I'm re-writing all of their components in full TypeScript with Material-UI, because I'm stubborn, lol.) I didn't have to do this.

### Regarding "WYSIWYG editors are slow"

Yes, WYSIWYG editors are very slow, in the sense that they generate "tag soup" (sometimes even invalid HTML, with lots of embedded `style=""` attributes, which in general is bad form, and hurts the browser's contentful paint load time.)

Since you're a self-professed beginner, consider the following:

- [What's so bad about in-line CSS?](https://stackoverflow.com/questions/2612483/whats-so-bad-about-in-line-css)
- [What are the risks associated with using inline styles?](https://stackoverflow.com/questions/41925390/what-are-the-risks-associated-with-using-inline-styles)

And in general, if you're allowing "random users" to use your editor, then **avoid any editor which allows users to copy-paste or hand-enter raw HTML code**, as this is the root of all evil when it comes to content exploits.

By contrast, **EditorJS outputs JSON, not HTML** -- and by default, [doesn't allow HTML](https://editorjs.io/sanitize-saved-data).

### Regarding "Flickering"

> Also do you experience flickering screen page with react-editor-js?

The only issue I experienced similar to this is when the insertion caret (text pointer) is above where you are trying to scroll, EditorJS (not `react-editor-js` fault) scrolls your browser up to where you're typing. It should be something you can suppress, but there's a bug where you can't suppress this at the moment. You can work around this issue rather easily (just give the editor enough room to breathe, such as a full screen editor as I've shown in my example.)

There are some default CSS rules in EditorJS itself that you might want to override to reduce this flickering, or due to quality of life / stylistic choices:

1) The default max-width is 650px, and we're not in 2000 anymore, so...

    ```css
    .ce-block__content,
    .ce-toolbar__content {
      max-width: 1024px;
    }
    ```

2) The editor adds 300px margin-bottom to allow for easy insertion, which makes "flickering" worse if your editor doesn't have at least 300px of space to work with in the page, such as a comment editor, but you can easily override this with CSS too:

    ```css
    .codex-editor__redactor {
      margin-bottom: -200px; /* padding is set using style="", so we can't
                                override directly, but setting a matching
                                negative margin does exactly the same thing. */
    }
    ```

**Comment by codigoisaac** [comment]
@AlbinoGeek I see, and you have good points, but I tried some editors (draftjs, quill, editorjs), and TinyMCE was and it's being the best experience. I needed to implement image upload and image resize, and it simply was so painful to find information and to implement it with others, and none of them has image resize, except TinyMCE and Draftjs-plugins - but Draftjs-plugins has a documentation that doesn't work and Draftjs is being discontinued by Facebook...

With TinyMCE things just worked and we could move on to actually building our software.
