### ISSUE TITLE
Can you create plugins that are React components?

### ISSUE THREAD

**Issue by marksboyce** [Jungwoo-An/react-editor-js#69]
Hi, thanks for all your hard work. 

I assume it isn't possible out-of-the-box to use React components as plugins, correct? It doesn't seem that way, but I'm just making sure.

Thanks.

**Comment by Jungwoo-An** [comment]
@marksboyce Hi! First of all, thanks for your interest! 👋 

You can't create plugin with react currently. (only vanila js)

I hope this [document](https://editorjs.io/the-first-plugin) will help you.

Thanks!

**Comment by marksboyce** [comment]
I thought not. Thanks.

**Comment by Benjaminryejones** [comment]
@marksboyce Not sure if this is what you meant, but custom tools can return jsx/react components

Here's a quick example:

```
class MyTool {
  render() {
    const container = document.createElement('div')
    ReactDOM.render(
      <ReactComponent />,
      container
    )

    return container
  }

  save(blockContent) {
    return {
      myData: blockContent.value,
    }
  }
}
```

[Also see this thread for caveats about onClick events](https://github.com/codex-team/editor.js/issues/1051#issuecomment-600112792)

**Comment by marksboyce** [comment]
@Benjaminryejones Thanks, this is useful. I started down this path, but I get the feeling that the lack of native support for React will make the whole thing a lot harder.

**Comment by natterstefan** [comment]
Hi @marksboyce,

This is indeed an interesting question. I've implemented EditorJS in several React apps and there are certain issues you need to be aware of. Not only regarding the onClick handling, but also other aspects.

Take a look at this example for instance: In a simple use-case where you add a React component (as I mentioned in the [another issue](https://github.com/codex-team/editor.js/issues/1051#issuecomment-600112792)), you end up with the following React app tree:

![image](https://user-images.githubusercontent.com/1043668/93989828-adb73280-fd8a-11ea-9d95-1856a4ca16d4.png)
_([example](https://codesandbox.io/s/jolly-cherry-us2mv))_

Because we are using `ReactDOM.render` here, two new trees will be added to the document. You have your `App` and two `ReactComponent`s. This is important if you want to work with an `AppContext` for instance (or Redux). Because the two React components cannot access it directly. They are independent Apps, seen in this way. Keep that in mind, as this caused some trouble for me at first.

I plan to write an article about how I solved this in my apps. But I do not have an ETA for the article yet.

**Comment by marksboyce** [comment]
@natterstefan Thanks for this. Helpful to know, and please share your article, once complete. These are the sorts of issues that I'm worried about banging my head against.

**Comment by donfour** [comment]
> @marksboyce Not sure if this is what you meant, but custom tools can return jsx/react components
> 
> Here's a quick example:
> 
> ```
> class MyTool {
>   render() {
>     const container = document.createElement('div')
>     ReactDOM.render(
>       <ReactComponent />,
>       container
>     )
> 
>     return container
>   }
> 
>   save(blockContent) {
>     return {
>       myData: blockContent.value,
>     }
>   }
> }
> ```
> 
> [Also see this thread for caveats about onClick events](https://github.com/codex-team/editor.js/issues/1051#issuecomment-600112792)

As this pattern seems pretty common, I extracted out the logic and wrote a util function: https://gist.github.com/donfour/82193ab0c138afcc8c840c7a79474db4. Hope it's useful.

**Comment by PurplePineapple123** [comment]
> I plan to write an article about how I solved this in my apps. But I do not have an ETA for the article yet.

Hey @natterstefan! Did you ever figure out how to prevent custom blocks from rendering in a different DOM? I was having trouble for a few days until I realized that my custom component was rendering in a different DOM and wasn't able to access redux.

**Comment by mikahFSmusic** [comment]
Hey @natterstefan, 

I know you can't share the code/too much detail, but can share a little more detail on how you implemented the callbacks? Did you have to fork editor.js/modify its source in order to do this? I'm trying to have a react component inside of a block that can read from a react context that's higher up in the component tree but have been struggling to find a method of implementation I'm happy with. 

If I can get something reasonable working, I'd be happy to open source the work and add it as a contribution to editor.js if appropriate. I imagine a tool like this would make editor.js infinitely more adoptable by the react community.
